crm/urls.py
from crm.settings import STATIC_ROOT, STATIC_URL
from django.conf import settings
from django.conf.urls.static import static
from leads.views import LandingPageView, SignupView, DashboardView
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView
)
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('nutritionists/', include('nutritionists.urls', namespace='nutritionists')),

    path('reset-password', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nutritionists/urls.py
from django.urls import path
from .views import (
    NutritionistListView, 
    NutritionistCreateView, 
    NutritionistDetailView, 
    NutritionistUpdateView, 
    NutritionistDeleteView
)

app_name = "nutritionists"

urlpatterns = [
    path('', NutritionistListView.as_view(), name='nutritionist-list'),
    path('<int:pk>/', NutritionistDetailView.as_view(), name='nutritionist-detail'),
    path('<int:pk>/update/', NutritionistUpdateView.as_view(), name='nutritionist-update'),
    path('<int:pk>/delete/', NutritionistDeleteView.as_view(), name='nutritionist-delete'),
    path('create/', NutritionistCreateView.as_view(), name='nutritionist-create')
]

nutritionists/models.py
from django.db import models

# Create your models here.

nutritionists/forms.py
from django import forms
from django.forms import fields
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class NutritionistModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email'
        )


        

nutritionists/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.views import generic
from leads.models import Nutritionist
from .forms import NutritionistModelForm
from .mixins import OrganiserAndLoginRequiredMixin

class NutritionistListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name= "nutritionists/nutritionist_list.html"
    
    def get_queryset(self):
        organization = self.request.user.organization
        return Nutritionist.objects.filter(organization=organization)


class NutritionistCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = "nutritionists/nutritionist_create.html"
    form_class = NutritionistModelForm

    def get_success_url(self):
        return reverse("nutritionists:nutritionist-list")

    def form_valid(self, form):
        user = form.save(commit=False) 
        user.is_organiser = False
        user.is_nutritionist = True
        user.set_password(f"{random.randint(0, 100000)}")
        user.save()  
        Nutritionist.objects.create(
            user=user,
            organization=self.request.user.organization
        )
        send_mail(
            subject="You are invited to be a Nutritionist",
            message="You were added as a nutritionist on ECF Participants Service. Please go to the service and use your email to reset default password and set up new one.",
            from_email="admin@test.com",
            recipient_list=[user.email]
        )
        return super(NutritionistCreateView, self).form_valid(form)


    
class NutritionistDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
    template_name = "nutritionists/nutritionist_detail.html"
    context_object_name = "nutritionist"

    def get_queryset(self):
        organization = self.request.user.organization
        return Nutritionist.objects.filter(organization=organization)


class NutritionistUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = "nutritionists/nutritionist_update.html"
    form_class = NutritionistModelForm
    
    def get_success_url(self):
        return reverse("nutritionists:nutritionist-list")

    def get_queryset(self):
        organization = self.request.user.organization
        return Nutritionist.objects.filter(organization=organization)

class NutritionistDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = "nutritionists/nutritionist_delete.html"
    context_object_name = "nutritionist"

    def get_queryset(self):
        organization = self.request.user.organization
        return Nutritionist.objects.filter(organization=organization)

    def get_success_url(self):
        return reverse("nutritionists:nutritionist-list")

    

nutritionists/templates/nutritionists/nutritionist_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <div class="py-5 border-t border-gray-200">
                    <h1 class="text-4xl text-gray-800">Create new nutritionist</h1>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

nutritionists/templates/nutritionists/nutritionist_delete.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h1>Are you sure you want to delete this nutritionist?</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class=" mt-3 flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Submit</button>
            </form>
        </div>
    </div>
  </div>
</section>
{% endblock content %}

nutritionists/templates/nutritionists/nutritionist_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Nutritionist</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ nutritionist.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'nutritionists:nutritionist-detail' nutritionist.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'nutritionists:nutritionist-update' nutritionist.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ nutritionist.user.first_name }} {{ nutritionist.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ nutritionist.user.email }}</span>
            </div>
            <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                <span class="text-gray-500">Date joined</span>
                <span class="ml-auto text-gray-900">{{ nutritionist.user.date_joined }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

nutritionists/templates/nutritionists/nutritionist_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Nutritionists</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'nutritionists:nutritionist-create' %}">Create a new nutritionist</a>
                </div>
            </div>
            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Full Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Email
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for nutritionist in object_list %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ nutritionist.user.first_name }} {{ nutritionist.user.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ nutritionist.user.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'nutritionists:nutritionist-update' nutritionist.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}
                            <p>There are currently no Nutritionists in the system.</p>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>
        </div>
      </section>
{% endblock content %}

nutritionists/templates/nutritionists/nutritionist_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Nutritionist</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ nutritionist.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'nutritionists:nutritionist-detail' nutritionist.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'nutritionists:nutritionist-update' nutritionist.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Submit</button>
            </form>
            <a href="{% url 'nutritionists:nutritionist-delete' nutritionist.pk %}" class="w-1/2 mt-3 flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-700 rounded">
                Delete
            </a>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}