crm/urls.py
from crm.settings import STATIC_ROOT, STATIC_URL
from django.conf import settings
from django.conf.urls.static import static
from leads.views import LandingPageView, SignupView, DashboardView
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView
)
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('nutritionists/', include('nutritionists.urls', namespace='nutritionists')),

    path('reset-password', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from leads.views import (
    LeadListView, 
    LeadDetailView, 
    LeadCreateView, 
    LeadUpdateView, 
    LeadDeleteView, 

    AssignNutritionistView, 
    LeadCategoryUpdateView,

    CategoryListView, 
    CategoryDetailView, 
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,

    FollowUpCreateView,
    FollowUpUpdateView,
    FollowUpDeleteView
    )

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),

    path('<int:pk>/assign-nutritionist/', AssignNutritionistView.as_view(), name='assign-nutritionist'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete', FollowUpDeleteView.as_view(), name='lead-followup-delete'),

    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create')
]

nutritionists/urls.py
from django.urls import path
from .views import (
    NutritionistListView, 
    NutritionistCreateView, 
    NutritionistDetailView, 
    NutritionistUpdateView, 
    NutritionistDeleteView
)

app_name = "nutritionists"

urlpatterns = [
    path('', NutritionistListView.as_view(), name='nutritionist-list'),
    path('<int:pk>/', NutritionistDetailView.as_view(), name='nutritionist-detail'),
    path('<int:pk>/update/', NutritionistUpdateView.as_view(), name='nutritionist-update'),
    path('<int:pk>/delete/', NutritionistDeleteView.as_view(), name='nutritionist-delete'),
    path('create/', NutritionistCreateView.as_view(), name='nutritionist-create')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
   
        <title>CRM | Nutritionist</title>
        
        <link href="{% static 'css/styles.css' %}" rel='stylesheet' />
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <!--link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}"-->
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
        
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="max-w-7xl mx-auto">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{% if message.tags == 'success' %}bg-green-500 text-white{% endif %}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            {% block content %}{% endblock content %}
        </div>
        {% include "scripts.html" %}
    </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM Dashboard
        </h1>
    
        <div class="flex flex-wrap -m-4 text-center">
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                    <path d="M8 17l4 4 4-4m-4-5v9"></path>
                    <path d="M20.88 18.09A5 5 0 0018 9h-1.26A8 8 0 103 16.29"></path>
                </svg>
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_lead_count }}</h2>
                <p class="leading-relaxed">Total Leads</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                    <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"></path>
                    <circle cx="9" cy="7" r="4"></circle>
                    <path d="M23 21v-2a4 4 0 00-3-3.87m-4-12a4 4 0 010 7.75"></path>
                </svg>
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_in_past30 }}</h2>
                <p class="leading-relaxed">Leads added in last 30 days</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                    <path d="M3 18v-6a9 9 0 0118 0v6"></path>
                    <path d="M21 19a2 2 0 01-2 2h-1a2 2 0 01-2-2v-3a2 2 0 012-2h3zM3 19a2 2 0 002 2h1a2 2 0 002-2v-3a2 2 0 00-2-2H3z"></path>
                </svg>
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ converted_in_past30 }}</h2>
                <p class="leading-relaxed">Converted in last 30 days</p>
                </div>
            </div>
        </div>
        
      </div>
    </div>
</section>
{% endblock content %}

templates/landing.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'logo.jpg' %}">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">CRM Nutritionists build with Django</h1>
      <p class="mb-8 leading-relaxed">
        This CRM helps an admin to manage potential participants and assign their cases to the specific nutritionists.
      </p>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
{% load static %}

<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-2 flex-col md:flex-row items-center">
    <a href="{% url 'dashboard' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <span class="ml-3 text-xl">CRM Nutritionist</span>
    </a>
    
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
    {% if request.user.is_authenticated %}
      <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>

      {% if request.user.is_organiser %}
        <a href="{% url 'nutritionists:nutritionist-list' %}" class="mr-5 hover:text-gray-900">Nutritionist</a>
      
      {% endif %}
      <a href="{% url 'logout' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      <a>
      <a class="inline-flex items-center">
        <span class="flex-grow flex flex-col pl-4">
          <span class="title-font font-medium text-gray-900 px-4">Welcome {{ request.user.username }}</span>
          <span class="text-gray-400 text-xs tracking-widest mt-0.5 px-4">{{ request.user.nutritionist.organization }}</span>
        </span>
      </a>
      {% else %}
      <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      <a>
      </nav>
    {% endif %}    
  </div>
  <hr />
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>